// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_TNyz1ble5OyPtaIjnLmVch0tIy_CPXQ',
    appId: '1:198160381905:web:9a4944306fcd2da67252f0',
    messagingSenderId: '198160381905',
    projectId: 'faselane',
    authDomain: 'faselane.firebaseapp.com',
    storageBucket: 'faselane.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoS2290DB15ff88hzDAqysQ5UPxJ-oaqU',
    appId: '1:198160381905:android:8dcb1912b0b581f57252f0',
    messagingSenderId: '198160381905',
    projectId: 'faselane',
    storageBucket: 'faselane.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWnUpShAdHH3TzgomeKo3gxG4dQ_5t3OM',
    appId: '1:198160381905:ios:147fac20459665da7252f0',
    messagingSenderId: '198160381905',
    projectId: 'faselane',
    storageBucket: 'faselane.firebasestorage.app',
    iosBundleId: 'com.example.fastLane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWnUpShAdHH3TzgomeKo3gxG4dQ_5t3OM',
    appId: '1:198160381905:ios:147fac20459665da7252f0',
    messagingSenderId: '198160381905',
    projectId: 'faselane',
    storageBucket: 'faselane.firebasestorage.app',
    iosBundleId: 'com.example.fastLane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_TNyz1ble5OyPtaIjnLmVch0tIy_CPXQ',
    appId: '1:198160381905:web:ed35d82b5a5fcc3d7252f0',
    messagingSenderId: '198160381905',
    projectId: 'faselane',
    authDomain: 'faselane.firebaseapp.com',
    storageBucket: 'faselane.firebasestorage.app',
  );
}
