
default_platform(:android)

platform :android do
  desc "Distribute the app to the testers"
  lane :distribute do
    firebase_app_distribution(
      app: "1:198160381905:android:8dcb1912b0b581f57252f0",
      groups: "testers",
      android_artifact_type: "APK",
      android_artifact_path: "app/build/outputs/apk/release/app-release.apk",
      release_notes: "Release notes",
      testers: mohandabdlsattar@gmai.com,  
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
    )
  end  
end
